version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
