/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateNavbarRouteRouteImport } from './routes/_private/_navbar/route'
import { Route as publicMeshRouteRouteImport } from './routes/(public)/_mesh/route'
import { Route as PrivateDevicesVerifyRouteImport } from './routes/_private/devices/verify'
import { Route as publicMeshLoginRouteImport } from './routes/(public)/_mesh/login'
import { Route as publicMeshActivateUserRouteImport } from './routes/(public)/_mesh/activate-user'
import { Route as publicMeshActivateServerRouteImport } from './routes/(public)/_mesh/activate-server'
import { Route as PrivateNavbarSettingsRouteRouteImport } from './routes/_private/_navbar/settings/route'
import { Route as PrivateNavbarFlowsRouteRouteImport } from './routes/_private/_navbar/flows/route'
import { Route as PrivateNavbarSettingsIndexRouteImport } from './routes/_private/_navbar/settings/index'
import { Route as PrivateNavbarFlowsIndexRouteImport } from './routes/_private/_navbar/flows/index'
import { Route as PrivateNavbarExecutionsIndexRouteImport } from './routes/_private/_navbar/executions/index'
import { Route as PrivateNavbarSettingsSecretsRouteImport } from './routes/_private/_navbar/settings/secrets'
import { Route as PrivateNavbarSettingsProfileRouteImport } from './routes/_private/_navbar/settings/profile'
import { Route as PrivateNavbarSettingsMembersRouteImport } from './routes/_private/_navbar/settings/members'
import { Route as PrivateNavbarSettingsApiKeysRouteImport } from './routes/_private/_navbar/settings/api-keys'
import { Route as PrivateNavbarFlowsFlowIdRouteRouteImport } from './routes/_private/_navbar/flows/$flowId/route'
import { Route as PrivateNavbarSettingsSecretsIndexRouteImport } from './routes/_private/_navbar/settings/secrets/index'
import { Route as PrivateNavbarFlowsFlowIdIndexRouteImport } from './routes/_private/_navbar/flows/$flowId/index'
import { Route as PrivateNavbarSettingsSecretsSecretIdRouteImport } from './routes/_private/_navbar/settings/secrets/$secretId'
import { Route as PrivateNavbarFlowsFlowIdVVersionRouteRouteImport } from './routes/_private/_navbar/flows/$flowId/v/$version/route'
import { Route as PrivateNavbarFlowsFlowIdExecutionsExecutionIdRouteRouteImport } from './routes/_private/_navbar/flows/$flowId/executions/$executionId/route'
import { Route as PrivateNavbarFlowsFlowIdVVersionIndexRouteImport } from './routes/_private/_navbar/flows/$flowId/v/$version/index'
import { Route as PrivateNavbarFlowsFlowIdVVersionTabsRouteRouteImport } from './routes/_private/_navbar/flows/$flowId/v/$version/_tabs/route'
import { Route as PrivateNavbarFlowsFlowIdVVersionTabsTabRouteImport } from './routes/_private/_navbar/flows/$flowId/v/$version/_tabs/$tab'
import { Route as PrivateNavbarFlowsFlowIdVVersionExecutionsExecutionIdRouteRouteImport } from './routes/_private/_navbar/flows/$flowId/v/$version/executions/$executionId/route'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateNavbarRouteRoute = PrivateNavbarRouteRouteImport.update({
  id: '/_navbar',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const publicMeshRouteRoute = publicMeshRouteRouteImport.update({
  id: '/(public)/_mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateDevicesVerifyRoute = PrivateDevicesVerifyRouteImport.update({
  id: '/devices/verify',
  path: '/devices/verify',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const publicMeshLoginRoute = publicMeshLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicMeshRouteRoute,
} as any)
const publicMeshActivateUserRoute = publicMeshActivateUserRouteImport.update({
  id: '/activate-user',
  path: '/activate-user',
  getParentRoute: () => publicMeshRouteRoute,
} as any)
const publicMeshActivateServerRoute =
  publicMeshActivateServerRouteImport.update({
    id: '/activate-server',
    path: '/activate-server',
    getParentRoute: () => publicMeshRouteRoute,
  } as any)
const PrivateNavbarSettingsRouteRoute =
  PrivateNavbarSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => PrivateNavbarRouteRoute,
  } as any)
const PrivateNavbarFlowsRouteRoute = PrivateNavbarFlowsRouteRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => PrivateNavbarRouteRoute,
} as any)
const PrivateNavbarSettingsIndexRoute =
  PrivateNavbarSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateNavbarSettingsRouteRoute,
  } as any)
const PrivateNavbarFlowsIndexRoute = PrivateNavbarFlowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateNavbarFlowsRouteRoute,
} as any)
const PrivateNavbarExecutionsIndexRoute =
  PrivateNavbarExecutionsIndexRouteImport.update({
    id: '/executions/',
    path: '/executions/',
    getParentRoute: () => PrivateNavbarRouteRoute,
  } as any)
const PrivateNavbarSettingsSecretsRoute =
  PrivateNavbarSettingsSecretsRouteImport.update({
    id: '/secrets',
    path: '/secrets',
    getParentRoute: () => PrivateNavbarSettingsRouteRoute,
  } as any)
const PrivateNavbarSettingsProfileRoute =
  PrivateNavbarSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => PrivateNavbarSettingsRouteRoute,
  } as any)
const PrivateNavbarSettingsMembersRoute =
  PrivateNavbarSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => PrivateNavbarSettingsRouteRoute,
  } as any)
const PrivateNavbarSettingsApiKeysRoute =
  PrivateNavbarSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => PrivateNavbarSettingsRouteRoute,
  } as any)
const PrivateNavbarFlowsFlowIdRouteRoute =
  PrivateNavbarFlowsFlowIdRouteRouteImport.update({
    id: '/$flowId',
    path: '/$flowId',
    getParentRoute: () => PrivateNavbarFlowsRouteRoute,
  } as any)
const PrivateNavbarSettingsSecretsIndexRoute =
  PrivateNavbarSettingsSecretsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateNavbarSettingsSecretsRoute,
  } as any)
const PrivateNavbarFlowsFlowIdIndexRoute =
  PrivateNavbarFlowsFlowIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateNavbarFlowsFlowIdRouteRoute,
  } as any)
const PrivateNavbarSettingsSecretsSecretIdRoute =
  PrivateNavbarSettingsSecretsSecretIdRouteImport.update({
    id: '/$secretId',
    path: '/$secretId',
    getParentRoute: () => PrivateNavbarSettingsSecretsRoute,
  } as any)
const PrivateNavbarFlowsFlowIdVVersionRouteRoute =
  PrivateNavbarFlowsFlowIdVVersionRouteRouteImport.update({
    id: '/v/$version',
    path: '/v/$version',
    getParentRoute: () => PrivateNavbarFlowsFlowIdRouteRoute,
  } as any)
const PrivateNavbarFlowsFlowIdExecutionsExecutionIdRouteRoute =
  PrivateNavbarFlowsFlowIdExecutionsExecutionIdRouteRouteImport.update({
    id: '/executions/$executionId',
    path: '/executions/$executionId',
    getParentRoute: () => PrivateNavbarFlowsFlowIdRouteRoute,
  } as any)
const PrivateNavbarFlowsFlowIdVVersionIndexRoute =
  PrivateNavbarFlowsFlowIdVVersionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateNavbarFlowsFlowIdVVersionRouteRoute,
  } as any)
const PrivateNavbarFlowsFlowIdVVersionTabsRouteRoute =
  PrivateNavbarFlowsFlowIdVVersionTabsRouteRouteImport.update({
    id: '/_tabs',
    getParentRoute: () => PrivateNavbarFlowsFlowIdVVersionRouteRoute,
  } as any)
const PrivateNavbarFlowsFlowIdVVersionTabsTabRoute =
  PrivateNavbarFlowsFlowIdVVersionTabsTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => PrivateNavbarFlowsFlowIdVVersionTabsRouteRoute,
  } as any)
const PrivateNavbarFlowsFlowIdVVersionExecutionsExecutionIdRouteRoute =
  PrivateNavbarFlowsFlowIdVVersionExecutionsExecutionIdRouteRouteImport.update({
    id: '/executions/$executionId',
    path: '/executions/$executionId',
    getParentRoute: () => PrivateNavbarFlowsFlowIdVVersionRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/flows': typeof PrivateNavbarFlowsRouteRouteWithChildren
  '/settings': typeof PrivateNavbarSettingsRouteRouteWithChildren
  '/activate-server': typeof publicMeshActivateServerRoute
  '/activate-user': typeof publicMeshActivateUserRoute
  '/login': typeof publicMeshLoginRoute
  '/devices/verify': typeof PrivateDevicesVerifyRoute
  '/flows/$flowId': typeof PrivateNavbarFlowsFlowIdRouteRouteWithChildren
  '/settings/api-keys': typeof PrivateNavbarSettingsApiKeysRoute
  '/settings/members': typeof PrivateNavbarSettingsMembersRoute
  '/settings/profile': typeof PrivateNavbarSettingsProfileRoute
  '/settings/secrets': typeof PrivateNavbarSettingsSecretsRouteWithChildren
  '/executions/': typeof PrivateNavbarExecutionsIndexRoute
  '/flows/': typeof PrivateNavbarFlowsIndexRoute
  '/settings/': typeof PrivateNavbarSettingsIndexRoute
  '/settings/secrets/$secretId': typeof PrivateNavbarSettingsSecretsSecretIdRoute
  '/flows/$flowId/': typeof PrivateNavbarFlowsFlowIdIndexRoute
  '/settings/secrets/': typeof PrivateNavbarSettingsSecretsIndexRoute
  '/flows/$flowId/executions/$executionId': typeof PrivateNavbarFlowsFlowIdExecutionsExecutionIdRouteRoute
  '/flows/$flowId/v/$version': typeof PrivateNavbarFlowsFlowIdVVersionTabsRouteRouteWithChildren
  '/flows/$flowId/v/$version/': typeof PrivateNavbarFlowsFlowIdVVersionIndexRoute
  '/flows/$flowId/v/$version/executions/$executionId': typeof PrivateNavbarFlowsFlowIdVVersionExecutionsExecutionIdRouteRoute
  '/flows/$flowId/v/$version/$tab': typeof PrivateNavbarFlowsFlowIdVVersionTabsTabRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/activate-server': typeof publicMeshActivateServerRoute
  '/activate-user': typeof publicMeshActivateUserRoute
  '/login': typeof publicMeshLoginRoute
  '/devices/verify': typeof PrivateDevicesVerifyRoute
  '/settings/api-keys': typeof PrivateNavbarSettingsApiKeysRoute
  '/settings/members': typeof PrivateNavbarSettingsMembersRoute
  '/settings/profile': typeof PrivateNavbarSettingsProfileRoute
  '/executions': typeof PrivateNavbarExecutionsIndexRoute
  '/flows': typeof PrivateNavbarFlowsIndexRoute
  '/settings': typeof PrivateNavbarSettingsIndexRoute
  '/settings/secrets/$secretId': typeof PrivateNavbarSettingsSecretsSecretIdRoute
  '/flows/$flowId': typeof PrivateNavbarFlowsFlowIdIndexRoute
  '/settings/secrets': typeof PrivateNavbarSettingsSecretsIndexRoute
  '/flows/$flowId/executions/$executionId': typeof PrivateNavbarFlowsFlowIdExecutionsExecutionIdRouteRoute
  '/flows/$flowId/v/$version': typeof PrivateNavbarFlowsFlowIdVVersionIndexRoute
  '/flows/$flowId/v/$version/executions/$executionId': typeof PrivateNavbarFlowsFlowIdVVersionExecutionsExecutionIdRouteRoute
  '/flows/$flowId/v/$version/$tab': typeof PrivateNavbarFlowsFlowIdVVersionTabsTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/(public)/_mesh': typeof publicMeshRouteRouteWithChildren
  '/_private/_navbar': typeof PrivateNavbarRouteRouteWithChildren
  '/_private/': typeof PrivateIndexRoute
  '/_private/_navbar/flows': typeof PrivateNavbarFlowsRouteRouteWithChildren
  '/_private/_navbar/settings': typeof PrivateNavbarSettingsRouteRouteWithChildren
  '/(public)/_mesh/activate-server': typeof publicMeshActivateServerRoute
  '/(public)/_mesh/activate-user': typeof publicMeshActivateUserRoute
  '/(public)/_mesh/login': typeof publicMeshLoginRoute
  '/_private/devices/verify': typeof PrivateDevicesVerifyRoute
  '/_private/_navbar/flows/$flowId': typeof PrivateNavbarFlowsFlowIdRouteRouteWithChildren
  '/_private/_navbar/settings/api-keys': typeof PrivateNavbarSettingsApiKeysRoute
  '/_private/_navbar/settings/members': typeof PrivateNavbarSettingsMembersRoute
  '/_private/_navbar/settings/profile': typeof PrivateNavbarSettingsProfileRoute
  '/_private/_navbar/settings/secrets': typeof PrivateNavbarSettingsSecretsRouteWithChildren
  '/_private/_navbar/executions/': typeof PrivateNavbarExecutionsIndexRoute
  '/_private/_navbar/flows/': typeof PrivateNavbarFlowsIndexRoute
  '/_private/_navbar/settings/': typeof PrivateNavbarSettingsIndexRoute
  '/_private/_navbar/settings/secrets/$secretId': typeof PrivateNavbarSettingsSecretsSecretIdRoute
  '/_private/_navbar/flows/$flowId/': typeof PrivateNavbarFlowsFlowIdIndexRoute
  '/_private/_navbar/settings/secrets/': typeof PrivateNavbarSettingsSecretsIndexRoute
  '/_private/_navbar/flows/$flowId/executions/$executionId': typeof PrivateNavbarFlowsFlowIdExecutionsExecutionIdRouteRoute
  '/_private/_navbar/flows/$flowId/v/$version': typeof PrivateNavbarFlowsFlowIdVVersionRouteRouteWithChildren
  '/_private/_navbar/flows/$flowId/v/$version/_tabs': typeof PrivateNavbarFlowsFlowIdVVersionTabsRouteRouteWithChildren
  '/_private/_navbar/flows/$flowId/v/$version/': typeof PrivateNavbarFlowsFlowIdVVersionIndexRoute
  '/_private/_navbar/flows/$flowId/v/$version/executions/$executionId': typeof PrivateNavbarFlowsFlowIdVVersionExecutionsExecutionIdRouteRoute
  '/_private/_navbar/flows/$flowId/v/$version/_tabs/$tab': typeof PrivateNavbarFlowsFlowIdVVersionTabsTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flows'
    | '/settings'
    | '/activate-server'
    | '/activate-user'
    | '/login'
    | '/devices/verify'
    | '/flows/$flowId'
    | '/settings/api-keys'
    | '/settings/members'
    | '/settings/profile'
    | '/settings/secrets'
    | '/executions/'
    | '/flows/'
    | '/settings/'
    | '/settings/secrets/$secretId'
    | '/flows/$flowId/'
    | '/settings/secrets/'
    | '/flows/$flowId/executions/$executionId'
    | '/flows/$flowId/v/$version'
    | '/flows/$flowId/v/$version/'
    | '/flows/$flowId/v/$version/executions/$executionId'
    | '/flows/$flowId/v/$version/$tab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate-server'
    | '/activate-user'
    | '/login'
    | '/devices/verify'
    | '/settings/api-keys'
    | '/settings/members'
    | '/settings/profile'
    | '/executions'
    | '/flows'
    | '/settings'
    | '/settings/secrets/$secretId'
    | '/flows/$flowId'
    | '/settings/secrets'
    | '/flows/$flowId/executions/$executionId'
    | '/flows/$flowId/v/$version'
    | '/flows/$flowId/v/$version/executions/$executionId'
    | '/flows/$flowId/v/$version/$tab'
  id:
    | '__root__'
    | '/_private'
    | '/(public)/_mesh'
    | '/_private/_navbar'
    | '/_private/'
    | '/_private/_navbar/flows'
    | '/_private/_navbar/settings'
    | '/(public)/_mesh/activate-server'
    | '/(public)/_mesh/activate-user'
    | '/(public)/_mesh/login'
    | '/_private/devices/verify'
    | '/_private/_navbar/flows/$flowId'
    | '/_private/_navbar/settings/api-keys'
    | '/_private/_navbar/settings/members'
    | '/_private/_navbar/settings/profile'
    | '/_private/_navbar/settings/secrets'
    | '/_private/_navbar/executions/'
    | '/_private/_navbar/flows/'
    | '/_private/_navbar/settings/'
    | '/_private/_navbar/settings/secrets/$secretId'
    | '/_private/_navbar/flows/$flowId/'
    | '/_private/_navbar/settings/secrets/'
    | '/_private/_navbar/flows/$flowId/executions/$executionId'
    | '/_private/_navbar/flows/$flowId/v/$version'
    | '/_private/_navbar/flows/$flowId/v/$version/_tabs'
    | '/_private/_navbar/flows/$flowId/v/$version/'
    | '/_private/_navbar/flows/$flowId/v/$version/executions/$executionId'
    | '/_private/_navbar/flows/$flowId/v/$version/_tabs/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  publicMeshRouteRoute: typeof publicMeshRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/_navbar': {
      id: '/_private/_navbar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateNavbarRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/(public)/_mesh': {
      id: '/(public)/_mesh'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicMeshRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/devices/verify': {
      id: '/_private/devices/verify'
      path: '/devices/verify'
      fullPath: '/devices/verify'
      preLoaderRoute: typeof PrivateDevicesVerifyRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/(public)/_mesh/login': {
      id: '/(public)/_mesh/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicMeshLoginRouteImport
      parentRoute: typeof publicMeshRouteRoute
    }
    '/(public)/_mesh/activate-user': {
      id: '/(public)/_mesh/activate-user'
      path: '/activate-user'
      fullPath: '/activate-user'
      preLoaderRoute: typeof publicMeshActivateUserRouteImport
      parentRoute: typeof publicMeshRouteRoute
    }
    '/(public)/_mesh/activate-server': {
      id: '/(public)/_mesh/activate-server'
      path: '/activate-server'
      fullPath: '/activate-server'
      preLoaderRoute: typeof publicMeshActivateServerRouteImport
      parentRoute: typeof publicMeshRouteRoute
    }
    '/_private/_navbar/settings': {
      id: '/_private/_navbar/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateNavbarSettingsRouteRouteImport
      parentRoute: typeof PrivateNavbarRouteRoute
    }
    '/_private/_navbar/flows': {
      id: '/_private/_navbar/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof PrivateNavbarFlowsRouteRouteImport
      parentRoute: typeof PrivateNavbarRouteRoute
    }
    '/_private/_navbar/settings/': {
      id: '/_private/_navbar/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof PrivateNavbarSettingsIndexRouteImport
      parentRoute: typeof PrivateNavbarSettingsRouteRoute
    }
    '/_private/_navbar/flows/': {
      id: '/_private/_navbar/flows/'
      path: '/'
      fullPath: '/flows/'
      preLoaderRoute: typeof PrivateNavbarFlowsIndexRouteImport
      parentRoute: typeof PrivateNavbarFlowsRouteRoute
    }
    '/_private/_navbar/executions/': {
      id: '/_private/_navbar/executions/'
      path: '/executions'
      fullPath: '/executions/'
      preLoaderRoute: typeof PrivateNavbarExecutionsIndexRouteImport
      parentRoute: typeof PrivateNavbarRouteRoute
    }
    '/_private/_navbar/settings/secrets': {
      id: '/_private/_navbar/settings/secrets'
      path: '/secrets'
      fullPath: '/settings/secrets'
      preLoaderRoute: typeof PrivateNavbarSettingsSecretsRouteImport
      parentRoute: typeof PrivateNavbarSettingsRouteRoute
    }
    '/_private/_navbar/settings/profile': {
      id: '/_private/_navbar/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof PrivateNavbarSettingsProfileRouteImport
      parentRoute: typeof PrivateNavbarSettingsRouteRoute
    }
    '/_private/_navbar/settings/members': {
      id: '/_private/_navbar/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof PrivateNavbarSettingsMembersRouteImport
      parentRoute: typeof PrivateNavbarSettingsRouteRoute
    }
    '/_private/_navbar/settings/api-keys': {
      id: '/_private/_navbar/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof PrivateNavbarSettingsApiKeysRouteImport
      parentRoute: typeof PrivateNavbarSettingsRouteRoute
    }
    '/_private/_navbar/flows/$flowId': {
      id: '/_private/_navbar/flows/$flowId'
      path: '/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof PrivateNavbarFlowsFlowIdRouteRouteImport
      parentRoute: typeof PrivateNavbarFlowsRouteRoute
    }
    '/_private/_navbar/settings/secrets/': {
      id: '/_private/_navbar/settings/secrets/'
      path: '/'
      fullPath: '/settings/secrets/'
      preLoaderRoute: typeof PrivateNavbarSettingsSecretsIndexRouteImport
      parentRoute: typeof PrivateNavbarSettingsSecretsRoute
    }
    '/_private/_navbar/flows/$flowId/': {
      id: '/_private/_navbar/flows/$flowId/'
      path: '/'
      fullPath: '/flows/$flowId/'
      preLoaderRoute: typeof PrivateNavbarFlowsFlowIdIndexRouteImport
      parentRoute: typeof PrivateNavbarFlowsFlowIdRouteRoute
    }
    '/_private/_navbar/settings/secrets/$secretId': {
      id: '/_private/_navbar/settings/secrets/$secretId'
      path: '/$secretId'
      fullPath: '/settings/secrets/$secretId'
      preLoaderRoute: typeof PrivateNavbarSettingsSecretsSecretIdRouteImport
      parentRoute: typeof PrivateNavbarSettingsSecretsRoute
    }
    '/_private/_navbar/flows/$flowId/v/$version': {
      id: '/_private/_navbar/flows/$flowId/v/$version'
      path: '/v/$version'
      fullPath: '/flows/$flowId/v/$version'
      preLoaderRoute: typeof PrivateNavbarFlowsFlowIdVVersionRouteRouteImport
      parentRoute: typeof PrivateNavbarFlowsFlowIdRouteRoute
    }
    '/_private/_navbar/flows/$flowId/executions/$executionId': {
      id: '/_private/_navbar/flows/$flowId/executions/$executionId'
      path: '/executions/$executionId'
      fullPath: '/flows/$flowId/executions/$executionId'
      preLoaderRoute: typeof PrivateNavbarFlowsFlowIdExecutionsExecutionIdRouteRouteImport
      parentRoute: typeof PrivateNavbarFlowsFlowIdRouteRoute
    }
    '/_private/_navbar/flows/$flowId/v/$version/': {
      id: '/_private/_navbar/flows/$flowId/v/$version/'
      path: '/'
      fullPath: '/flows/$flowId/v/$version/'
      preLoaderRoute: typeof PrivateNavbarFlowsFlowIdVVersionIndexRouteImport
      parentRoute: typeof PrivateNavbarFlowsFlowIdVVersionRouteRoute
    }
    '/_private/_navbar/flows/$flowId/v/$version/_tabs': {
      id: '/_private/_navbar/flows/$flowId/v/$version/_tabs'
      path: ''
      fullPath: '/flows/$flowId/v/$version'
      preLoaderRoute: typeof PrivateNavbarFlowsFlowIdVVersionTabsRouteRouteImport
      parentRoute: typeof PrivateNavbarFlowsFlowIdVVersionRouteRoute
    }
    '/_private/_navbar/flows/$flowId/v/$version/_tabs/$tab': {
      id: '/_private/_navbar/flows/$flowId/v/$version/_tabs/$tab'
      path: '/$tab'
      fullPath: '/flows/$flowId/v/$version/$tab'
      preLoaderRoute: typeof PrivateNavbarFlowsFlowIdVVersionTabsTabRouteImport
      parentRoute: typeof PrivateNavbarFlowsFlowIdVVersionTabsRouteRoute
    }
    '/_private/_navbar/flows/$flowId/v/$version/executions/$executionId': {
      id: '/_private/_navbar/flows/$flowId/v/$version/executions/$executionId'
      path: '/executions/$executionId'
      fullPath: '/flows/$flowId/v/$version/executions/$executionId'
      preLoaderRoute: typeof PrivateNavbarFlowsFlowIdVVersionExecutionsExecutionIdRouteRouteImport
      parentRoute: typeof PrivateNavbarFlowsFlowIdVVersionRouteRoute
    }
  }
}

interface PrivateNavbarFlowsFlowIdVVersionTabsRouteRouteChildren {
  PrivateNavbarFlowsFlowIdVVersionTabsTabRoute: typeof PrivateNavbarFlowsFlowIdVVersionTabsTabRoute
}

const PrivateNavbarFlowsFlowIdVVersionTabsRouteRouteChildren: PrivateNavbarFlowsFlowIdVVersionTabsRouteRouteChildren =
  {
    PrivateNavbarFlowsFlowIdVVersionTabsTabRoute:
      PrivateNavbarFlowsFlowIdVVersionTabsTabRoute,
  }

const PrivateNavbarFlowsFlowIdVVersionTabsRouteRouteWithChildren =
  PrivateNavbarFlowsFlowIdVVersionTabsRouteRoute._addFileChildren(
    PrivateNavbarFlowsFlowIdVVersionTabsRouteRouteChildren,
  )

interface PrivateNavbarFlowsFlowIdVVersionRouteRouteChildren {
  PrivateNavbarFlowsFlowIdVVersionTabsRouteRoute: typeof PrivateNavbarFlowsFlowIdVVersionTabsRouteRouteWithChildren
  PrivateNavbarFlowsFlowIdVVersionIndexRoute: typeof PrivateNavbarFlowsFlowIdVVersionIndexRoute
  PrivateNavbarFlowsFlowIdVVersionExecutionsExecutionIdRouteRoute: typeof PrivateNavbarFlowsFlowIdVVersionExecutionsExecutionIdRouteRoute
}

const PrivateNavbarFlowsFlowIdVVersionRouteRouteChildren: PrivateNavbarFlowsFlowIdVVersionRouteRouteChildren =
  {
    PrivateNavbarFlowsFlowIdVVersionTabsRouteRoute:
      PrivateNavbarFlowsFlowIdVVersionTabsRouteRouteWithChildren,
    PrivateNavbarFlowsFlowIdVVersionIndexRoute:
      PrivateNavbarFlowsFlowIdVVersionIndexRoute,
    PrivateNavbarFlowsFlowIdVVersionExecutionsExecutionIdRouteRoute:
      PrivateNavbarFlowsFlowIdVVersionExecutionsExecutionIdRouteRoute,
  }

const PrivateNavbarFlowsFlowIdVVersionRouteRouteWithChildren =
  PrivateNavbarFlowsFlowIdVVersionRouteRoute._addFileChildren(
    PrivateNavbarFlowsFlowIdVVersionRouteRouteChildren,
  )

interface PrivateNavbarFlowsFlowIdRouteRouteChildren {
  PrivateNavbarFlowsFlowIdIndexRoute: typeof PrivateNavbarFlowsFlowIdIndexRoute
  PrivateNavbarFlowsFlowIdExecutionsExecutionIdRouteRoute: typeof PrivateNavbarFlowsFlowIdExecutionsExecutionIdRouteRoute
  PrivateNavbarFlowsFlowIdVVersionRouteRoute: typeof PrivateNavbarFlowsFlowIdVVersionRouteRouteWithChildren
}

const PrivateNavbarFlowsFlowIdRouteRouteChildren: PrivateNavbarFlowsFlowIdRouteRouteChildren =
  {
    PrivateNavbarFlowsFlowIdIndexRoute: PrivateNavbarFlowsFlowIdIndexRoute,
    PrivateNavbarFlowsFlowIdExecutionsExecutionIdRouteRoute:
      PrivateNavbarFlowsFlowIdExecutionsExecutionIdRouteRoute,
    PrivateNavbarFlowsFlowIdVVersionRouteRoute:
      PrivateNavbarFlowsFlowIdVVersionRouteRouteWithChildren,
  }

const PrivateNavbarFlowsFlowIdRouteRouteWithChildren =
  PrivateNavbarFlowsFlowIdRouteRoute._addFileChildren(
    PrivateNavbarFlowsFlowIdRouteRouteChildren,
  )

interface PrivateNavbarFlowsRouteRouteChildren {
  PrivateNavbarFlowsFlowIdRouteRoute: typeof PrivateNavbarFlowsFlowIdRouteRouteWithChildren
  PrivateNavbarFlowsIndexRoute: typeof PrivateNavbarFlowsIndexRoute
}

const PrivateNavbarFlowsRouteRouteChildren: PrivateNavbarFlowsRouteRouteChildren =
  {
    PrivateNavbarFlowsFlowIdRouteRoute:
      PrivateNavbarFlowsFlowIdRouteRouteWithChildren,
    PrivateNavbarFlowsIndexRoute: PrivateNavbarFlowsIndexRoute,
  }

const PrivateNavbarFlowsRouteRouteWithChildren =
  PrivateNavbarFlowsRouteRoute._addFileChildren(
    PrivateNavbarFlowsRouteRouteChildren,
  )

interface PrivateNavbarSettingsSecretsRouteChildren {
  PrivateNavbarSettingsSecretsSecretIdRoute: typeof PrivateNavbarSettingsSecretsSecretIdRoute
  PrivateNavbarSettingsSecretsIndexRoute: typeof PrivateNavbarSettingsSecretsIndexRoute
}

const PrivateNavbarSettingsSecretsRouteChildren: PrivateNavbarSettingsSecretsRouteChildren =
  {
    PrivateNavbarSettingsSecretsSecretIdRoute:
      PrivateNavbarSettingsSecretsSecretIdRoute,
    PrivateNavbarSettingsSecretsIndexRoute:
      PrivateNavbarSettingsSecretsIndexRoute,
  }

const PrivateNavbarSettingsSecretsRouteWithChildren =
  PrivateNavbarSettingsSecretsRoute._addFileChildren(
    PrivateNavbarSettingsSecretsRouteChildren,
  )

interface PrivateNavbarSettingsRouteRouteChildren {
  PrivateNavbarSettingsApiKeysRoute: typeof PrivateNavbarSettingsApiKeysRoute
  PrivateNavbarSettingsMembersRoute: typeof PrivateNavbarSettingsMembersRoute
  PrivateNavbarSettingsProfileRoute: typeof PrivateNavbarSettingsProfileRoute
  PrivateNavbarSettingsSecretsRoute: typeof PrivateNavbarSettingsSecretsRouteWithChildren
  PrivateNavbarSettingsIndexRoute: typeof PrivateNavbarSettingsIndexRoute
}

const PrivateNavbarSettingsRouteRouteChildren: PrivateNavbarSettingsRouteRouteChildren =
  {
    PrivateNavbarSettingsApiKeysRoute: PrivateNavbarSettingsApiKeysRoute,
    PrivateNavbarSettingsMembersRoute: PrivateNavbarSettingsMembersRoute,
    PrivateNavbarSettingsProfileRoute: PrivateNavbarSettingsProfileRoute,
    PrivateNavbarSettingsSecretsRoute:
      PrivateNavbarSettingsSecretsRouteWithChildren,
    PrivateNavbarSettingsIndexRoute: PrivateNavbarSettingsIndexRoute,
  }

const PrivateNavbarSettingsRouteRouteWithChildren =
  PrivateNavbarSettingsRouteRoute._addFileChildren(
    PrivateNavbarSettingsRouteRouteChildren,
  )

interface PrivateNavbarRouteRouteChildren {
  PrivateNavbarFlowsRouteRoute: typeof PrivateNavbarFlowsRouteRouteWithChildren
  PrivateNavbarSettingsRouteRoute: typeof PrivateNavbarSettingsRouteRouteWithChildren
  PrivateNavbarExecutionsIndexRoute: typeof PrivateNavbarExecutionsIndexRoute
}

const PrivateNavbarRouteRouteChildren: PrivateNavbarRouteRouteChildren = {
  PrivateNavbarFlowsRouteRoute: PrivateNavbarFlowsRouteRouteWithChildren,
  PrivateNavbarSettingsRouteRoute: PrivateNavbarSettingsRouteRouteWithChildren,
  PrivateNavbarExecutionsIndexRoute: PrivateNavbarExecutionsIndexRoute,
}

const PrivateNavbarRouteRouteWithChildren =
  PrivateNavbarRouteRoute._addFileChildren(PrivateNavbarRouteRouteChildren)

interface PrivateRouteRouteChildren {
  PrivateNavbarRouteRoute: typeof PrivateNavbarRouteRouteWithChildren
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateDevicesVerifyRoute: typeof PrivateDevicesVerifyRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateNavbarRouteRoute: PrivateNavbarRouteRouteWithChildren,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateDevicesVerifyRoute: PrivateDevicesVerifyRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface publicMeshRouteRouteChildren {
  publicMeshActivateServerRoute: typeof publicMeshActivateServerRoute
  publicMeshActivateUserRoute: typeof publicMeshActivateUserRoute
  publicMeshLoginRoute: typeof publicMeshLoginRoute
}

const publicMeshRouteRouteChildren: publicMeshRouteRouteChildren = {
  publicMeshActivateServerRoute: publicMeshActivateServerRoute,
  publicMeshActivateUserRoute: publicMeshActivateUserRoute,
  publicMeshLoginRoute: publicMeshLoginRoute,
}

const publicMeshRouteRouteWithChildren = publicMeshRouteRoute._addFileChildren(
  publicMeshRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  publicMeshRouteRoute: publicMeshRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
