name: Release-pipeline

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get the version from the github tag ref
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: lts/*
          package-manager-cache: false

      - name: Install pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
        with:
          version: 10

      - name: Install dependencies and build
        run: |
          pnpm install --frozen-lockfile
          pnpm build
        env:
          VITE_UI_VERSION: ${{ steps.get_version.outputs.VERSION }}
          VITE_ANALYTICS_SERVER_URL: https://analytics.zenml.io/batch

      - name: Create release archive
        run: |
          tar -zcf kitaru-ui.tar.gz -C dist --transform="s#\.\/##" .
          sha256sum -b kitaru-ui.tar.gz > kitaru-ui.tar.gz.sha256

      - name: Release to GitHub
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: |
            kitaru-ui.tar.gz
            kitaru-ui.tar.gz.sha256
          body_path: ./CHANGELOG.md
          prerelease: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
